apiVersion: v1
kind: Secret
metadata:
  name: gitlab-jira-manual-hook-elasticsearch
  namespace: gitlab-jira-manual-hook
type: Opaque
stringData:
  ELASTICSEARCH_URL: https://elasticsearch.example.com:443
  ELASTICSEARCH_API_KEY: replace-me
